hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt3GeV/V5 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt3GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt2GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt2GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt4GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt4GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt5GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt5GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt7GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt7GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt10GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt10GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt15GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt15GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt20GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt20GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt30GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt30GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/Pt999GeV/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > Pt999GeV.py &

hltGetConfiguration /users/sdonato/2024Jan/ScoutingTracking/TimingHighPtTracking/GRunV14/V1 --globaltag 124X_mcRun3_2022_realistic_v12 --mc --unprescale --output none --max-events 100 --input file:/eos/user/p/pellicci/MesonGamma_root/2023/Wpipipi_RAW/Wpluspipipi_RAW2023_27.root --eras Run3 --output none --paths DST_Run3_JetHT_PFScoutingPixelTracking_* --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml --customise mycustomisation.replaceTrackMerger > GRunV14.py &


